INSERT INTO PERSONS (LASTNAME,NAME,PROGAMING_LANGUAGE ) VALUES ('Ruiz','Andres','Java')
INSERT INTO PERSONS (LASTNAME,NAME,PROGAMING_LANGUAGE ) VALUES ('Ramirez','Tadeo','Java')
INSERT INTO PERSONS (LASTNAME,NAME,PROGAMING_LANGUAGE ) VALUES ('Perez','Simon','Java')